/*
 * Decompiled with CFR 0.139.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.client.renderer.RenderHelper
 *  net.minecraft.entity.Entity
 *  org.lwjgl.opengl.GL11
 */
package com.mayakplay.cscase.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.RenderHelper;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelGuiCase
extends ModelBase {
    ModelRenderer Fence = new ModelRenderer((ModelBase)this, 0, 0);
    ModelRenderer Fence1;
    ModelRenderer Fence2;
    ModelRenderer Fence3;
    ModelRenderer Fence4;
    ModelRenderer Fence5;
    ModelRenderer Fence6;
    ModelRenderer Fence7;
    ModelRenderer Fence8;
    ModelRenderer Fence9;
    ModelRenderer Fence10;
    ModelRenderer Fence11;
    ModelRenderer Fence12;
    ModelRenderer Back;
    ModelRenderer Back1;
    ModelRenderer Back2;
    ModelRenderer Back3;
    ModelRenderer Back4;
    ModelRenderer Stay;
    ModelRenderer Stay1;
    ModelRenderer Block;

    public ModelGuiCase() {
        this(0.0f);
    }

    public ModelGuiCase(float par1) {
        this.Fence.setTextureSize(128, 128);
        this.Fence.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence.setRotationPoint(0.0f, 23.5f, 0.0f);
        this.Fence1 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Fence1.setTextureSize(128, 128);
        this.Fence1.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence1.setRotationPoint(0.0f, 20.5f, 0.0f);
        this.Fence2 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Fence2.setTextureSize(128, 128);
        this.Fence2.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence2.setRotationPoint(0.0f, 17.5f, 0.0f);
        this.Fence3 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Fence3.setTextureSize(128, 128);
        this.Fence3.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence3.setRotationPoint(0.0f, 14.5f, 0.0f);
        this.Fence4 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Fence4.setTextureSize(128, 128);
        this.Fence4.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence4.setRotationPoint(0.0f, 11.5f, 0.0f);
        this.Fence5 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Fence5.setTextureSize(128, 128);
        this.Fence5.addBox(-0.5f, -0.5f, -16.0f, 1, 1, 32);
        this.Fence5.setRotationPoint(0.0f, 8.5f, 0.0f);
        this.Fence6 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence6.setTextureSize(128, 128);
        this.Fence6.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence6.setRotationPoint(-0.13f, 16.5f, -15.5f);
        this.Fence7 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence7.setTextureSize(128, 128);
        this.Fence7.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence7.setRotationPoint(-0.13f, 16.5f, 15.5f);
        this.Fence8 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence8.setTextureSize(128, 128);
        this.Fence8.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence8.setRotationPoint(-0.13f, 16.5f, 0.0f);
        this.Fence9 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence9.setTextureSize(128, 128);
        this.Fence9.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence9.setRotationPoint(-0.13f, 16.5f, 11.0f);
        this.Fence10 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence10.setTextureSize(128, 128);
        this.Fence10.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence10.setRotationPoint(-0.13f, 16.5f, 5.0f);
        this.Fence11 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence11.setTextureSize(128, 128);
        this.Fence11.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence11.setRotationPoint(-0.13f, 16.5f, -11.0f);
        this.Fence12 = new ModelRenderer((ModelBase)this, 17, 17);
        this.Fence12.setTextureSize(128, 128);
        this.Fence12.addBox(-0.5f, -0.5f, -7.5f, 1, 1, 15);
        this.Fence12.setRotationPoint(-0.13f, 16.5f, -5.0f);
        this.Back = new ModelRenderer((ModelBase)this, 0, 33);
        this.Back.setTextureSize(128, 128);
        this.Back.addBox(-0.5f, -8.0f, -16.0f, 1, 16, 32);
        this.Back.setRotationPoint(-17.0f, 16.0f, 0.0f);
        this.Back1 = new ModelRenderer((ModelBase)this, 0, 33);
        this.Back1.setTextureSize(128, 128);
        this.Back1.addBox(-0.5f, -8.0f, -16.0f, 1, 16, 32);
        this.Back1.setRotationPoint(-8.5f, 23.5f, 0.0f);
        this.Back2 = new ModelRenderer((ModelBase)this, 0, 33);
        this.Back2.setTextureSize(128, 128);
        this.Back2.addBox(-0.5f, -8.0f, -16.0f, 1, 16, 32);
        this.Back2.setRotationPoint(-8.5f, 8.5f, 0.0f);
        this.Back3 = new ModelRenderer((ModelBase)this, 15, 64);
        this.Back3.setTextureSize(128, 128);
        this.Back3.addBox(-8.0f, -8.0f, -0.5f, 16, 16, 1);
        this.Back3.setRotationPoint(-8.5f, 16.36f, -15.5f);
        this.Back4 = new ModelRenderer((ModelBase)this, 15, 64);
        this.Back4.setTextureSize(128, 128);
        this.Back4.addBox(-8.0f, -8.0f, -0.5f, 16, 16, 1);
        this.Back4.setRotationPoint(-8.5f, 16.36f, 15.5f);
        this.Stay = new ModelRenderer((ModelBase)this, 35, 0);
        this.Stay.setTextureSize(128, 128);
        this.Stay.addBox(-3.0f, -0.5f, -11.0f, 6, 1, 22);
        this.Stay.setRotationPoint(-9.0f, 18.0f, 0.6217537f);
        this.Stay1 = new ModelRenderer((ModelBase)this, 71, 4);
        this.Stay1.setTextureSize(128, 128);
        this.Stay1.addBox(-1.0f, -3.5f, -4.5f, 2, 7, 9);
        this.Stay1.setRotationPoint(-8.291135f, 22.32676f, 0.6217537f);
        this.Block = new ModelRenderer((ModelBase)this, 0, 0);
        this.Block.setTextureSize(128, 128);
        this.Block.addBox(-0.5f, -2.0f, -1.5f, 1, 4, 3);
        this.Block.setRotationPoint(-3.0f, 6.0f, -11.0f);
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
        this.Fence.rotateAngleX = 0.0f;
        this.Fence.rotateAngleY = 0.0f;
        this.Fence.rotateAngleZ = 0.0f;
        this.Fence.renderWithRotation(par7);
        this.Fence1.rotateAngleX = 0.0f;
        this.Fence1.rotateAngleY = 0.0f;
        this.Fence1.rotateAngleZ = 0.0f;
        this.Fence1.renderWithRotation(par7);
        this.Fence2.rotateAngleX = 0.0f;
        this.Fence2.rotateAngleY = 0.0f;
        this.Fence2.rotateAngleZ = 0.0f;
        this.Fence2.renderWithRotation(par7);
        this.Fence3.rotateAngleX = 0.0f;
        this.Fence3.rotateAngleY = 0.0f;
        this.Fence3.rotateAngleZ = 0.0f;
        this.Fence3.renderWithRotation(par7);
        this.Fence4.rotateAngleX = 0.0f;
        this.Fence4.rotateAngleY = 0.0f;
        this.Fence4.rotateAngleZ = 0.0f;
        this.Fence4.renderWithRotation(par7);
        this.Fence5.rotateAngleX = 0.0f;
        this.Fence5.rotateAngleY = 0.0f;
        this.Fence5.rotateAngleZ = 0.0f;
        this.Fence5.renderWithRotation(par7);
        this.Fence6.rotateAngleX = -1.570796f;
        this.Fence6.rotateAngleY = 0.0f;
        this.Fence6.rotateAngleZ = 0.0f;
        this.Fence6.renderWithRotation(par7);
        this.Fence7.rotateAngleX = -1.570796f;
        this.Fence7.rotateAngleY = 0.0f;
        this.Fence7.rotateAngleZ = 0.0f;
        this.Fence7.renderWithRotation(par7);
        this.Fence8.rotateAngleX = -1.570796f;
        this.Fence8.rotateAngleY = 0.0f;
        this.Fence8.rotateAngleZ = 0.0f;
        this.Fence8.renderWithRotation(par7);
        this.Fence9.rotateAngleX = -1.570796f;
        this.Fence9.rotateAngleY = 0.0f;
        this.Fence9.rotateAngleZ = 0.0f;
        this.Fence9.renderWithRotation(par7);
        this.Fence10.rotateAngleX = -1.570796f;
        this.Fence10.rotateAngleY = 0.0f;
        this.Fence10.rotateAngleZ = 0.0f;
        this.Fence10.renderWithRotation(par7);
        this.Fence11.rotateAngleX = -1.570796f;
        this.Fence11.rotateAngleY = 0.0f;
        this.Fence11.rotateAngleZ = 0.0f;
        this.Fence11.renderWithRotation(par7);
        this.Fence12.rotateAngleX = -1.570796f;
        this.Fence12.rotateAngleY = 0.0f;
        this.Fence12.rotateAngleZ = 0.0f;
        this.Fence12.renderWithRotation(par7);
        this.Back.rotateAngleX = 0.0f;
        this.Back.rotateAngleY = 0.0f;
        this.Back.rotateAngleZ = 0.0f;
        this.Back.renderWithRotation(par7);
        this.Back1.rotateAngleX = 0.0f;
        this.Back1.rotateAngleY = 0.0f;
        this.Back1.rotateAngleZ = -1.570796f;
        this.Back1.renderWithRotation(par7);
        this.Back2.rotateAngleX = 0.0f;
        this.Back2.rotateAngleY = 0.0f;
        this.Back2.rotateAngleZ = 1.570796f;
        this.Back2.renderWithRotation(par7);
        this.Back3.rotateAngleX = 0.0f;
        this.Back3.rotateAngleY = 0.0f;
        this.Back3.rotateAngleZ = -1.570796f;
        this.Back3.renderWithRotation(par7);
        this.Back4.rotateAngleX = 0.0f;
        this.Back4.rotateAngleY = 3.141593f;
        this.Back4.rotateAngleZ = -1.570796f;
        this.Back4.renderWithRotation(par7);
        this.Stay.rotateAngleX = 0.0f;
        this.Stay.rotateAngleY = 0.0f;
        this.Stay.rotateAngleZ = 0.3157104f;
        this.Stay.renderWithRotation(par7);
        this.Stay1.rotateAngleX = 0.0f;
        this.Stay1.rotateAngleY = 0.0f;
        this.Stay1.rotateAngleZ = 0.0f;
        this.Stay1.renderWithRotation(par7);
        this.Block.rotateAngleX = 0.0f;
        this.Block.rotateAngleY = 0.0f;
        this.Block.rotateAngleZ = 0.0f;
        this.Block.renderWithRotation(par7);
    }

    public void renderModel(float par7, float fencePos, float numPos) {
        GL11.glPushMatrix();
        GL11.glTranslatef((float)0.0f, (float)fencePos, (float)0.0f);
        this.Fence.rotateAngleX = 0.0f;
        this.Fence.rotateAngleY = 0.0f;
        this.Fence.rotateAngleZ = 0.0f;
        this.Fence.renderWithRotation(par7);
        this.Fence1.rotateAngleX = 0.0f;
        this.Fence1.rotateAngleY = 0.0f;
        this.Fence1.rotateAngleZ = 0.0f;
        this.Fence1.renderWithRotation(par7);
        this.Fence2.rotateAngleX = 0.0f;
        this.Fence2.rotateAngleY = 0.0f;
        this.Fence2.rotateAngleZ = 0.0f;
        this.Fence2.renderWithRotation(par7);
        this.Fence3.rotateAngleX = 0.0f;
        this.Fence3.rotateAngleY = 0.0f;
        this.Fence3.rotateAngleZ = 0.0f;
        this.Fence3.renderWithRotation(par7);
        this.Fence4.rotateAngleX = 0.0f;
        this.Fence4.rotateAngleY = 0.0f;
        this.Fence4.rotateAngleZ = 0.0f;
        this.Fence4.renderWithRotation(par7);
        this.Fence5.rotateAngleX = 0.0f;
        this.Fence5.rotateAngleY = 0.0f;
        this.Fence5.rotateAngleZ = 0.0f;
        this.Fence5.renderWithRotation(par7);
        this.Fence6.rotateAngleX = -1.570796f;
        this.Fence6.rotateAngleY = 0.0f;
        this.Fence6.rotateAngleZ = 0.0f;
        this.Fence6.renderWithRotation(par7);
        this.Fence7.rotateAngleX = -1.570796f;
        this.Fence7.rotateAngleY = 0.0f;
        this.Fence7.rotateAngleZ = 0.0f;
        this.Fence7.renderWithRotation(par7);
        this.Fence8.rotateAngleX = -1.570796f;
        this.Fence8.rotateAngleY = 0.0f;
        this.Fence8.rotateAngleZ = 0.0f;
        this.Fence8.renderWithRotation(par7);
        this.Fence9.rotateAngleX = -1.570796f;
        this.Fence9.rotateAngleY = 0.0f;
        this.Fence9.rotateAngleZ = 0.0f;
        this.Fence9.renderWithRotation(par7);
        this.Fence10.rotateAngleX = -1.570796f;
        this.Fence10.rotateAngleY = 0.0f;
        this.Fence10.rotateAngleZ = 0.0f;
        this.Fence10.renderWithRotation(par7);
        this.Fence11.rotateAngleX = -1.570796f;
        this.Fence11.rotateAngleY = 0.0f;
        this.Fence11.rotateAngleZ = 0.0f;
        this.Fence11.renderWithRotation(par7);
        this.Fence12.rotateAngleX = -1.570796f;
        this.Fence12.rotateAngleY = 0.0f;
        this.Fence12.rotateAngleZ = 0.0f;
        this.Fence12.renderWithRotation(par7);
        GL11.glPopMatrix();
        this.Back.rotateAngleX = 0.0f;
        this.Back.rotateAngleY = 0.0f;
        this.Back.rotateAngleZ = 0.0f;
        this.Back.renderWithRotation(par7);
        RenderHelper.enableGUIStandardItemLighting();
        this.Back1.rotateAngleX = 0.0f;
        this.Back1.rotateAngleY = 0.0f;
        this.Back1.rotateAngleZ = -1.570796f;
        this.Back1.renderWithRotation(par7);
        this.Back2.rotateAngleX = 0.0f;
        this.Back2.rotateAngleY = 0.0f;
        this.Back2.rotateAngleZ = 1.570796f;
        this.Back2.renderWithRotation(par7);
        this.Back3.rotateAngleX = 0.0f;
        this.Back3.rotateAngleY = 0.0f;
        this.Back3.rotateAngleZ = -1.570796f;
        this.Back3.renderWithRotation(par7);
        this.Back4.rotateAngleX = 0.0f;
        this.Back4.rotateAngleY = 3.141593f;
        this.Back4.rotateAngleZ = -1.570796f;
        this.Back4.renderWithRotation(par7);
        RenderHelper.disableStandardItemLighting();
        GL11.glPushMatrix();
        GL11.glTranslatef((float)0.0f, (float)numPos, (float)0.0f);
        this.Block.rotateAngleX = 0.0f;
        this.Block.rotateAngleY = 0.0f;
        this.Block.rotateAngleZ = 0.0f;
        this.Block.renderWithRotation(par7);
        GL11.glPopMatrix();
    }
}

